console.log("Hola Mundo")
console.log("hi World")
console.log("cómo estás?")
console.log("olá mundo")
console.log("Felicidades")
console.log("nice to meet you")
console.log("chau")
console.log("ciao")
console.log("hasta luego")
console.log("adeu")
